spring:
  application:
    name: auth-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/foundation_db?currentSchema=auth_schema
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yaml
    default-schema: auth_schema

logging:
  level:
    me.xpestilent.foundation.outbox: DEBUG

server:
  port: 8081

foundation:
  security:
    jwt:
      type:
        access: access
        refresh: refresh
        tokens: Bearer
      expiration:
        access: 3600000
        refresh: 2592000000
      algorithm: RSA
      issuer: auth-service
      public-key-path: classpath:keys/public_key.pem
      private-key-path: classpath:keys/private_key_pkcs8.der
      cleanup-cron: "*/10 * * * * *"

springdoc:
  api-docs:
    path: /v3/api-docs/auth