<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.10</version>
	</parent>

	<groupId>me.xpestilent</groupId>
	<artifactId>foundation</artifactId>
	<version>v0.1</version>
	<name>foundation</name>

	<description>Demo project for Spring Boot</description>

	<packaging>pom</packaging>

	<modules>
		<module>libs/foundation-web-starter</module>
        <module>libs/foundation-logging-starter</module>
        <module>services/user-service</module>
    </modules>


	<properties>
		<java.version>21</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<springdoc.version>3.0.1</springdoc.version>
		<lombok.version>1.18.42</lombok.version>
		<micrometer.version>1.6.3</micrometer.version>
		<logback.encoder.version>9.0</logback.encoder.version>
	</properties>


	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>me.xpestilent</groupId>
				<artifactId>foundation-logging-starter</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>me.xpestilent</groupId>
				<artifactId>foundation-web-starter</artifactId>
				<version>${project.version}</version>
			</dependency>

			<!-- Source: https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui -->
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
				<version>${springdoc.version}</version>
				<scope>compile</scope>
			</dependency>

			<!-- Source: https://mvnrepository.com/artifact/io.micrometer/micrometer-tracing-bridge-brave -->
			<dependency>
				<groupId>io.micrometer</groupId>
				<artifactId>micrometer-tracing-bridge-brave</artifactId>
				<version>${micrometer.version}</version>
				<scope>compile</scope>
			</dependency>

			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>

			<!-- Source: https://mvnrepository.com/artifact/net.logstash.logback/logstash-logback-encoder -->
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logback.encoder.version}</version>
				<scope>compile</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<skip>true</skip>
					</configuration>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.13.0</version>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
						<parameters>true</parameters>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
