server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**, /v3/api-docs/auth/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth
    enabled: true